### ISSUE TITLE
Determine if path is file or directory

### ISSUE THREAD

**Issue by petrgazarov** [IonicaBizau/node-is-there#19]
Hey @IonicaBizau,

Nice work on the project! It would be nice to be able to determine whether or not the path is a directory.

Similar to this:
```
var Fs = require("fs");
Fs.lstatSync('/usr').isDirectory();
```

There is an example where it would be an elegant solution to [this issue in cdnjs](https://github.com/cdnjs/cdnjs/issues/10073).

**Comment by IonicaBizau** [comment]
@petrgazarov Maybe something like:


```js
if (isThere.directory("/usr")) { ... }
if (isThere.file("/usr")) { ... }
```

Good idea! :+1:
