### ISSUE TITLE
Thank you!  :+1:

### ISSUE THREAD

**Issue by TheNotary** [IonicaBizau/node-is-there#8]
It's naive of the exists() planners to think that a dev would only be checking for file existence in order to write to that specific file.  I have a situation where I needed to figure out that actual root of the app so I could begin reading many different files.  My code would look like rubbish without using exists and adjusting root directories.

**Comment by IonicaBizau** [comment]
Hey @TheNotary! :sparkles: 

I'm glad you like it! That's why I created this library: to keep the code simple and clean. :smile: 
Cheers!
