### ISSUE TITLE
Errors swallowed by method

### ISSUE THREAD

**Issue by cdaringe** [IonicaBizau/node-is-there#9]
hello:

https://github.com/IonicaBizau/node-is-there/blob/master/lib/index.js#L14

Should this throw if not ENOENT?

**Comment by IonicaBizau** [comment]
Hey @cdaringe!

Thanks for this issue.
For convenience, no. I agree it could be improved, but currently I don't know how.

If I remember well, the `fs.exists` callback had only one argument: `exists`. There were no errors. How did they manage the other errors?

Maybe the best answer here is to check the code in the old versions of node. :sparkle:

**Comment by cdaringe** [comment]
If there is an EPERM, for example, you are just returning `false`.  Because of this, the user/consumer is mislead.  I'm not using this lib, but was checking out the src.  Something you may want to consider!  Thx

**Comment by IonicaBizau** [comment]
[Here](https://github.com/nodejs/node/blob/a363f61ca839e817eb6853c5dc5af8c3b9b9226b/lib/fs.js#L165-L181) you can see the implementation of `exists` and `existsSync`. As you can see, the only check is if there is an error. I may consider bringing that here. Now I understand your point.

Basically, just `err ? false : true`. :sparkles:

**Comment by IonicaBizau** [comment]
:ship: **`4.1.0`** :tada: Thanks again for the heads-up!
